import Head from "next/head";
import DownloadSection from "../components/DownloadSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Main from "../components/Main";

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen font-main">
      <Head>
        <title>Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <DownloadSection />
      <Footer />
    </div>
  );
}
